name: facsimilab
channels:
  - conda-forge
  # - bioconda
  - pytorch
  - nvidia

dependencies:
  # Python and interactive python
  - python=3.11
  - IPython=8.14
  - ipykernel=6.23
  - ipywidgets=8.0
  # - nb_conda_kernels=2.3
  - jupyter=1.0
  - jupyter-cache=0.6
  - nbformat=5.9
  - nbclient>0.7
  - six=1.16
  - mamba


  # General
  - tqdm=4.65
  - black=23.3
  - black-jupyter=23.3
  - click>8.1

  # Web
  - requests=2.31
  - urllib3

  # Version control
  - datalad=0.19

  # Data structures and analysis
  - pandas=2.1
  - numpy>1.23
  - scipy=1
  - pingouin=0.5
  - h5py=3
  - arrow=1.3
  - fastparquet=2023.10
  - python-igraph=0.10
  - xlsxwriter=3.1
  - pyreadstat=1.2

  # Visualization
  - matplotlib=3.8
  - seaborn>0.12 #=0.12
  - plotly=5.15
  - tabulate=0.9
  - pygraphviz=1.11

  # Machine Learning
  - lightning=2.0.1
  - leidenalg=0.9
  - louvain=0.8
  - hnswlib=0.7

  # # GPU
  # - jaxlib=*=12cuda*
  # - jax=0.4.11
  # - flax=0.6
  # - cuda-nvcc
  # - pytorch
  # - torchvision
  # - torchaudio
  # - pytorch-cuda=12.1 

  # Next-generation -omics
  - scanpy=1.9
  - scvi-tools=1.0
  - scikit-learn=1.*
  - scikit-image=0.22
  - scikit-misc=0.1
  # - scvelo=0.3
  # - bioconda::pydeseq2=0.4
  # - bioconda::gseapy=1.1
  # - bioconda::celltypist=1.6

  # # Primer design
  # - primer3-py

  # Automation
  - nbconvert=7.6
  - papermill=2.3

  # Documentation
  - pandoc=3.1
  - mdutils=1.6

  # # C  / C++
  # - cython=0.29.36

  # # R
  # - rpy2=3.5

  # pip
  - pip
  # - pip:
  #     - torch==2.3.1
  #     - torchaudio
  #     - torchvision
  #     - --extra-index-url https://download.pytorch.org/whl/cu121/torch_stable.html
  #     - jax[cuda12]
  #     - velocyto
  #     - pybind11
  #     - pyvis
